services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_DATABASE: deepflow
      MYSQL_ROOT_PASSWORD: deepflowdb123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./src/main/resources/data.csv:/docker-entrypoint-initdb.d/data.csv

  backend:
    build: .
    image: jjy12163/deepflow-backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql-data:
