server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/deepflowdb
    username: deepflowdb
    password: deepflow123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
  task:
    scheduling:
      pool:
        size: 5

gcp:
  storage:
    bucket: ${GCS_BUCKET}
    credentials: ${GCS_CREDENTIALS_JSON}
    project-id: ${GCP_PROJECT_ID}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
